name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      puppeteer:
        image: mcp/puppeteer:latest
        ports:
          - 8085:80

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[dev]
        
    - name: Wait for Puppeteer service
      run: |
        timeout 60 bash -c 'until curl -f http://localhost:8085/health || curl -f http://localhost:8085; do sleep 2; done'
        
    - name: Code quality checks
      run: |
        black --check src/ tests/
        flake8 src/ tests/ --max-line-length=88
        mypy src/ --ignore-missing-imports
        
    - name: Run tests
      run: |
        pytest --cov=src --cov-report=xml --cov-report=term-missing
        
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella